CREATE TABLE IF NOT EXISTS dronelogs (
  uuid varchar(36) PRIMARY KEY,
  file_name varchar(100) UNIQUE,
  decrypt_status BOOLEAN,
  -- ...
  -- ...
  -- ...
  -- ...
  started_at timestamp NOT NULL,
  completed_at timestamp
);
